---
- name: install freeradius
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - freeradius
    - freeradius-mysql
    - freeradius-utils
    - default-libmysqlclient-dev
    - mysql-client

- name: Ensure Pip is installed.
  package:
    name: python-pip
    state: present

- name: Install the MySQL-python through pip
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - MySQL-python
