---
- name: install freeradius
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items:
    - freeradius
    - freeradius-mysql
    - freeradius-ldap
    - freeradius-utils
    - default-libmysqlclient-dev
    - mysql-client
    - gpgv2 
    - gnupg2 
    - rng-tools

- name: Ensure Pip is installed.
  package:
    name: python-pip
    state: present

- name: Install the MySQL-python through pip
  pip:
    name: '{{ item }}'
    state: present
  with_items:
    - MySQL-python

- name: enable freeradius
  service:
    name: freeradius
    enabled: yes

- name: Creates directories
  file:
    path: '{{ item }}'
    state: directory
    owner: freerad
    group: freerad
  with_items:
    - /etc/freeradius/3.0/certs/newcerts
    - /etc/freeradius/3.0/certs/newcerts/private

- name: copy template certificates
  template:
    src: 'server.cnf.j2'
    dest: '/etc/freeradius/{{ freeradius_version }}/certs/newcerts/server.cnf'
  notify:
    restart freeradius

- name: Download ca.crt
  get_url:
    url: http://eduroam.uy/docs/ca.crt
    dest: /etc/freeradius/3.0/certs/newcerts/ca.crt
    mode: '0440'
    owner: freerad
    group: freerad

- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: /etc/freeradius/3.0/certs/newcerts/private/server.key
    passphrase: '{{ freeradius_password_ca }}'
    cipher: auto
    size: 4096
    state: present
    owner: freerad
    group: freerad

- name: Generate DH Parameters
  openssl_dhparam:
    path: /etc/freeradius/3.0/certs/newcerts/dh
    size: 1024
    owner: freerad
    group: freerad

- name: check if the random file exists
  stat:
    path: /etc/freeradius/3.0/certs/newcerts/random
  register: stat_result

- name: Generate a random string
  command: 'dd if=/dev/urandom of=./random count=10'
  args:
    chdir: /etc/freeradius/3.0/certs/newcerts
  when: stat_result.stat.exists == False

- name: Touch index.txt
  file:
    path: /etc/freeradius/3.0/certs/newcerts/index.txt
    state: touch
    owner: freerad
    group: freerad

- name: Copy file serial
  template:
    src: 'serial.j2'
    dest: '/etc/freeradius/3.0/certs/newcerts/serial'
    owner: freerad
    group: freerad

- name: Generate csr
  openssl_csr:
    path: '/etc/freeradius/3.0/certs/newcerts/radius.interior.csr'
    privatekey_path: '/etc/freeradius/3.0/certs/newcerts/private/server.key'
    country_name: '{{ freeradius_code_country }}'
    organization_name: '{{ freeradius_organization }}'
    email_address: '{{ freeradius_email }}'
    state_or_province_name: '{{ freeradius_state }}'
    common_name: '{{ freeradius_common_name }}'
    privatekey_passphrase: '{{ freeradius_password_ca }}'
    owner: freerad
    group: freerad
