---
- name: install freeradius
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items:
    - freeradius
    - freeradius-mysql
    - freeradius-ldap
    - freeradius-utils
    - default-libmysqlclient-dev
    - mariadb-client
    - mariadb-server
    - python-mysqldb

- name: enable freeradius
  service:
    name: freeradius
    enabled: yes
