---

- name: copy template config ldap
  template:
    src: ldap.j2
    dest: "/etc/freeradius/{{ freeradius_version }}/mods-available/ldap"
  notify:
    restart freeradius

- name: copy file config sites
  copy:
    src: 'files/{{ item }}'
    dest: "/etc/freeradius/{{ freeradius_version }}/sites-available/{{ item }}"
  with_items:
    - default
    - inner-tunnel
  notify:
    restart freeradius

- name: Activate ldap freeradius
  file:
    path: "/etc/freeradius/{{ freeradius_version }}/mods-enabled/ldap"
    src: "/etc/freeradius/{{ freeradius_version }}/mods-available/ldap"
    state: link
  notify: restart freeradius