---
- import_tasks: install.yml
- import_tasks: clients.yml

- name: INCLUDE | database mysql
  include_tasks: schemas.yml
  when: freeradius_system_users == 'mysql'

- import_tasks: log.yml

- name: INCLUDE | config user mysql
  include_tasks: mysql.yml
  when: freeradius_system_users == 'mysql'

- name: INCLUDE | config LDAP
  include_tasks: ldap.yml
  when: freeradius_system_users == 'ldap'

- name: INCLUDE | create certificates
  include_tasks: certificates.yml
  when: freeradius_create_certificates
